### ISSUE TITLE
quoted number data type not detected properly

### ISSUE THREAD

**Issue by austinsims** [austinsims/test-data-generator#2]
![image](https://cloud.githubusercontent.com/assets/788451/4745125/ee89ecf6-5a36-11e4-8104-7b2f5230b8d4.png)

**Comment by JeffSallans** [comment]
VersionID   ParticipantID   HistoryTypeID   StageID SignedServiceID State   UpdSeq
1   2529406 NULL    NULL    NULL    NULL    0

produces a Convert.ToDateTime("0") when should be 0

![image](https://cloud.githubusercontent.com/assets/1188772/4994324/f62a9c2c-6985-11e4-875c-b91db8915201.png)
